vpc_cidr      = "10.0.0.0/16"
ami_id        = "ami-0e35ddab05955cf57"
instance_type = "t2.micro"
bucket_name   = "Terraform_Module_Conf_Template"
region        = "ap-south-1"
aws_profile   = "default"
